name: Dokku deploy

on:
    push:
        branches:
          - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Repo checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Dokku Push
                uses: dokku/github-action@master
                with:
                    branch: 'main'
                    git_remote_url: 'ssh://dokku@${{ secrets.SSH_HOST }}:22/darksub-bot'
                    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
