name: Dokku deploy

on:
    push:
        branches:
          - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
            LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
            LAVALINK_PORT: ${{ secrets.LAVALINK_PORT }}
            LAVALINK_PASS: ${{ secrets.LAVALINK_PASS }}
            OWNERID: ${{ secrets.OWNERID }}
        steps:
            -   name: Repo checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1

            -   name: Dokku Push
                uses: dokku/github-action@master
                with:
                    branch: 'main'
                    git_remote_url: 'ssh://dokku@${{ secrets.SSH_HOST }}:22/darksub-bot'
                    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
